/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, Decal, RenderTexture, Text, PerspectiveCamera } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/room/door.glb?url'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    OBJ_1: THREE.Mesh
    OBJ_2: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshPhysicalMaterial
    Brass_A_5: THREE.MeshPhysicalMaterial
  }
}

export function RedrumDoor(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF(model) as GLTFResult
    const textRef = useRef()
    useFrame((state) => (textRef.current.position.x = Math.sin(state.clock.elapsedTime) * 1))
  
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.102, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
              <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.OBJ_1.geometry}
                  material={materials.Wood}
              >
                  {/* <planeGeometry args={[3.6 * 1000, 3.6* 1000]}></planeGeometry> */}
                  <Decal
                    debug
                    position={[0, 0, 0]}
                    rotation={[-Math.PI / 2, Math.PI, 0]}
                    scale={[0.9 * 100, 0.25 * 100, 1 * 100]}
                  >
                      <meshStandardMaterial roughness={1} transparent polygonOffset polygonOffsetFactor={-1}>
                          <RenderTexture attach="map" anisotropy={16}>
                              <PerspectiveCamera makeDefault manual aspect={0.9 / 0.25} rotation={[0, 0, 0]}  position={[0, 0, 2]} />
                              <color attach="background" args={['#af2040']} />
                              <ambientLight intensity={1} />
                              {/* <directionalLight position={[10, 10, 5]} /> */}
                              <Text
                                  position={[0, 0, 0]}
                                  rotation={[0, Math.PI, 0]}
                                  ref={textRef}
                                  fontSize={0.5} color="red">
                                    123456789
                                </Text>
                      </RenderTexture>
                      </meshStandardMaterial>
                    </Decal>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.OBJ_2.geometry}
          material={materials.Brass_A_5}
        />
      </group>
    </group>
  )
}

useGLTF.preload(model)
