// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
// import * as THREE from 'three'
// import type { MathProps, ReactProps, EventHandlers, InstanceProps } from '@react-three/fiber'
// import type { Mutable, Overwrite } from '@react-three/fiber/dist/declarations/src/core/utils'
// import type { JSX } from 'react/jsx-runtime'

// const MODEL_PATH = './assets/models/room/Desktop.glb'
// export function Desktop(props: JSX.IntrinsicAttributes & Mutable<Overwrite<Partial<Overwrite<THREE.Group<THREE.Object3DEventMap>, MathProps<THREE.Group<THREE.Object3DEventMap>> & ReactProps<THREE.Group<THREE.Object3DEventMap>> & Partial<EventHandlers>>>, Omit<InstanceProps<THREE.Group<THREE.Object3DEventMap>, typeof THREE.Group>, "object">>>) {
//   const { nodes, materials } = useGLTF(MODEL_PATH)
//   return (
//     <group {...props} dispose={null}>
//       <group position={[0.104, 0.63, 0.174]} rotation={[1.549, 1.453, -1.549]} scale={0.001}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={(nodes.Node1 as THREE.Mesh).geometry}
//           material={materials['#090909FF.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={(nodes.Node4 as THREE.Mesh).geometry}
//           material={materials['#404040FF.001']}
//           position={[0, -0.009, 0]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={(nodes.Node5 as THREE.Mesh).geometry}
//           material={materials['#7E7E7EFF.001']}
//           position={[0, -0.009, 0]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={(nodes.Node6 as THREE.Mesh).geometry}
//           material={materials['#FFFFFFFF.002']}
//           position={[0, -0.009, 0]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={(nodes.Node7 as THREE.Mesh).geometry}
//           material={materials['#339987FF.001']}
//           position={[0, -0.009, 0]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={(nodes.Node8 as THREE.Mesh).geometry}
//           material={materials['#FF5F1CFF.001']}
//           position={[0, -0.009, 0]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={(nodes.Node9 as THREE.Mesh).geometry}
//           material={materials['#E2A60BFF.001']}
//           position={[0, -0.009, 0]}
//         />
//       </group>
//       <group position={[-0.206, 0.621, 0.171]} rotation={[1.467, -1.568, -0.109]} scale={0.001}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={(nodes.Node5001 as THREE.Mesh).geometry}
//           material={materials['#C2D8E8FF.001']}
//           rotation={[-0.783, 1.564, -0.783]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={(nodes.Node6001 as THREE.Mesh).geometry}
//           material={materials['#204369FF.001']}
//           rotation={[-0.783, 1.564, -0.783]}
//         />
//       </group>
//       <group position={[0, 0.594, 0]} rotation={[0, 1.57, 0]} scale={0.001}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={(nodes.Node1001 as THREE.Mesh).geometry}
//           material={materials['Material.002']}
//           position={[-79.352, 0, 0.021]}
//         />
//       </group>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={(nodes.lamp_s as THREE.Mesh).geometry}
//         material={(nodes.lamp_s as THREE.Mesh).material}
//         position={[-0.182, 0.771, -0.432]}
//         rotation={[1.58, -0.005, -0.554]}
//         scale={1.5}
//       />
//     </group>
//   )
// }

// useGLTF.preload(MODEL_PATH)