/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/room/Desktop2.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    obj003: THREE.Mesh
    obj003_1: THREE.Mesh
    obj003_2: THREE.Mesh
    obj003_3: THREE.Mesh
    obj003_4: THREE.Mesh
    obj003_5: THREE.Mesh
    obj003_6: THREE.Mesh
    obj003_7: THREE.Mesh
    obj003_8: THREE.Mesh
    obj003_9: THREE.Mesh
    obj003_10: THREE.Mesh
    obj003_11: THREE.Mesh
    obj003_12: THREE.Mesh
    obj003_13: THREE.Mesh
    obj003_14: THREE.Mesh
    obj003_15: THREE.Mesh
    obj003_16: THREE.Mesh
    obj003_17: THREE.Mesh
    obj003_18: THREE.Mesh
    Node1001: THREE.Mesh
    Node2001: THREE.Mesh
    Node3001: THREE.Mesh
    Node4001: THREE.Mesh
    Node5001: THREE.Mesh
    Node6001: THREE.Mesh
    Node7001: THREE.Mesh
    Node8001: THREE.Mesh
    Node1002: THREE.Mesh
    Node2002: THREE.Mesh
    Node3002: THREE.Mesh
    Node1003: THREE.Mesh
    Node4002: THREE.Mesh
    Node5002: THREE.Mesh
    Node6: THREE.Mesh
    Node7: THREE.Mesh
    Node9001: THREE.Mesh
  }
  materials: {
    ['Mat.003']: THREE.MeshPhysicalMaterial
    ['Mat_1.003']: THREE.MeshPhysicalMaterial
    ['Mat_2.003']: THREE.MeshPhysicalMaterial
    ['Mat_3.003']: THREE.MeshPhysicalMaterial
    ['Latun2.003']: THREE.MeshPhysicalMaterial
    ['Wood_light.003']: THREE.MeshPhysicalMaterial
    ['Mat_4.003']: THREE.MeshPhysicalMaterial
    ['Mat_5.003']: THREE.MeshPhysicalMaterial
    ['Mat_8.003']: THREE.MeshPhysicalMaterial
    ['Mat_9.003']: THREE.MeshPhysicalMaterial
    ['Mat_10.003']: THREE.MeshPhysicalMaterial
    ['Mat_11.003']: THREE.MeshPhysicalMaterial
    ['Mat_12.003']: THREE.MeshPhysicalMaterial
    ['Mat_13.003']: THREE.MeshPhysicalMaterial
    ['Mat_14.003']: THREE.MeshPhysicalMaterial
    ['Mat_15.003']: THREE.MeshPhysicalMaterial
    ['Mat_16.003']: THREE.MeshPhysicalMaterial
    ['Mat_17.003']: THREE.MeshPhysicalMaterial
    ['Mat_18.003']: THREE.MeshPhysicalMaterial
    ['Loader.001']: THREE.MeshStandardMaterial
    Loader: THREE.MeshStandardMaterial
    Key: THREE.MeshStandardMaterial
    Cap: THREE.MeshStandardMaterial
    Frame: THREE.MeshStandardMaterial
    ['Frame.001']: THREE.MeshStandardMaterial
    Poles: THREE.MeshStandardMaterial
    ['#292929FF']: THREE.MeshStandardMaterial
    ['#0EAA49FF']: THREE.MeshPhysicalMaterial
    ['#C6901CFF']: THREE.MeshStandardMaterial
    ['#D3D6D3FF.001']: THREE.MeshStandardMaterial
    ['#0A7DB5FF.001']: THREE.MeshStandardMaterial
    ['#4C4C4CFF.001']: THREE.MeshStandardMaterial
    ['#895956FF']: THREE.MeshStandardMaterial
    ['#CAD1EEFF']: THREE.MeshStandardMaterial
    ['#FFFFFFFF.001']: THREE.MeshStandardMaterial
  }
}

export function Desktop2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.432, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003.geometry}
          material={materials['Mat.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_1.geometry}
          material={materials['Mat_1.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_2.geometry}
          material={materials['Mat_2.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_3.geometry}
          material={materials['Mat_3.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_4.geometry}
          material={materials['Latun2.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_5.geometry}
          material={materials['Wood_light.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_6.geometry}
          material={materials['Mat_4.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_7.geometry}
          material={materials['Mat_5.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_8.geometry}
          material={materials['Mat_8.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_9.geometry}
          material={materials['Mat_9.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_10.geometry}
          material={materials['Mat_10.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_11.geometry}
          material={materials['Mat_11.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_12.geometry}
          material={materials['Mat_12.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_13.geometry}
          material={materials['Mat_13.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_14.geometry}
          material={materials['Mat_14.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_15.geometry}
          material={materials['Mat_15.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_16.geometry}
          material={materials['Mat_16.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_17.geometry}
          material={materials['Mat_17.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_18.geometry}
          material={materials['Mat_18.003']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node1001.geometry}
        material={materials['Loader.001']}
        position={[0, 0.868, -0.157]}
        rotation={[1.569, 0, 3.14]}
        scale={0.03}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node2001.geometry}
          material={materials.Loader}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node3001.geometry}
          material={materials.Key}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node4001.geometry}
          material={materials.Key}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node5001.geometry}
          material={materials.Cap}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node6001.geometry}
          material={materials.Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node7001.geometry}
          material={materials['Frame.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node8001.geometry}
          material={materials.Poles}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node1002.geometry}
        material={materials['#292929FF']}
        position={[-0.378, 0.868, -0.137]}
        rotation={[-Math.PI, 0.715, -Math.PI]}
        scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node2002.geometry}
          material={materials['#0EAA49FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node3002.geometry}
          material={materials['#C6901CFF']}
          position={[0, 0.966, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node1003.geometry}
        material={materials['#D3D6D3FF.001']}
        position={[-0.419, 0.88, 0.163]}
        rotation={[-3.093, -0.89, 0.015]}
        scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node4002.geometry}
          material={materials['#0A7DB5FF.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node5002.geometry}
          material={materials['#4C4C4CFF.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node6.geometry}
          material={materials['#895956FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node7.geometry}
          material={materials['#CAD1EEFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node9001.geometry}
          material={materials['#FFFFFFFF.001']}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload(model)
