/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/room/Env2.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    Node1002: THREE.Mesh
    Node10001: THREE.Mesh
    Node2001: THREE.Mesh
    Node3001: THREE.Mesh
    Node4001: THREE.Mesh
    Node5001: THREE.Mesh
    Node6001: THREE.Mesh
    Node7001: THREE.Mesh
    Node8001: THREE.Mesh
    Node9001: THREE.Mesh
    Node1001: THREE.Mesh
    night_stand_2: THREE.Mesh
    night_stand_1: THREE.Mesh
    slap: THREE.Mesh
    Node1003: THREE.Mesh
    Node10002: THREE.Mesh
    Node11: THREE.Mesh
    Node12: THREE.Mesh
    Node13: THREE.Mesh
    Node14: THREE.Mesh
    Node15: THREE.Mesh
    Node16: THREE.Mesh
    Node17: THREE.Mesh
    Node18: THREE.Mesh
    Node2002: THREE.Mesh
    Node3002: THREE.Mesh
    Node4002: THREE.Mesh
    Node5002: THREE.Mesh
    Node6002: THREE.Mesh
    Node7002: THREE.Mesh
    Node8002: THREE.Mesh
    Node9002: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato_1: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato_2: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato_3: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato_4: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato_5: THREE.Mesh
    Node1: THREE.Mesh
    Node2: THREE.Mesh
    Node3: THREE.Mesh
    Node1004: THREE.Mesh
    Node2003: THREE.Mesh
    Node3003: THREE.Mesh
    OBJ: THREE.Mesh
    OBJ_1: THREE.Mesh
    stand: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001_1: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001_2: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001_3: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001_4: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001_5: THREE.Mesh
  }
  materials: {
    ['#BB935CFF.003']: THREE.MeshStandardMaterial
    ['#000000FF.003']: THREE.MeshStandardMaterial
    ['#855A1DFF.003']: THREE.MeshStandardMaterial
    ['#F2E2C5FF.003']: THREE.MeshStandardMaterial
    ['x1.002']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['#D7D0C0FF']: THREE.MeshStandardMaterial
    ['#F7E099FF']: THREE.MeshStandardMaterial
    ['#E5E5E5FF']: THREE.MeshStandardMaterial
    ['#57D669FF']: THREE.MeshStandardMaterial
    ['#CAD1EEFF']: THREE.MeshStandardMaterial
    ['#DBDBDBFF']: THREE.MeshStandardMaterial
    ['#C2662EFF']: THREE.MeshStandardMaterial
    ['#FFFFFFFF.003']: THREE.MeshStandardMaterial
    ['#A58300FF']: THREE.MeshStandardMaterial
    ['#1A1A1AFF']: THREE.MeshStandardMaterial
    ['#49A954FF']: THREE.MeshStandardMaterial
    ['Aluminum_-_Polished']: THREE.MeshPhysicalMaterial
    ['Fabric_(Generic)']: THREE.MeshPhysicalMaterial
    ['Paint_-_Enamel_Glossy_(Black)']: THREE.MeshPhysicalMaterial
    ['Paint_-_Metallic_(Blue)']: THREE.MeshPhysicalMaterial
    ['Paint_-_Enamel_Glossy_(Yellow)']: THREE.MeshPhysicalMaterial
    ['Paint_-_Metallic_(Dark_Grey)']: THREE.MeshPhysicalMaterial
    ['#181818FF.002']: THREE.MeshStandardMaterial
    ['#F5F5F2FF.001']: THREE.MeshPhysicalMaterial
    ['#F4F4F5FF.001']: THREE.MeshStandardMaterial
    ['#181818FF.003']: THREE.MeshStandardMaterial
    ['#F5F5F2FF.002']: THREE.MeshPhysicalMaterial
    ['#F4F4F5FF.002']: THREE.MeshStandardMaterial
    Wood: THREE.MeshPhysicalMaterial
    Brass_A_5: THREE.MeshPhysicalMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Aluminum_-_Polished.001']: THREE.MeshPhysicalMaterial
    ['Fabric_(Generic).001']: THREE.MeshPhysicalMaterial
    ['Paint_-_Enamel_Glossy_(Black).001']: THREE.MeshPhysicalMaterial
    ['Paint_-_Metallic_(Blue).001']: THREE.MeshPhysicalMaterial
    ['Paint_-_Enamel_Glossy_(Yellow).001']: THREE.MeshPhysicalMaterial
    ['Paint_-_Metallic_(Dark_Grey).001']: THREE.MeshPhysicalMaterial
  }
}

export function Room2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[1.498, -0.047, 2.728]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1002.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node10001.geometry}
          material={materials['#000000FF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node2001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node3001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node4001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node5001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node6001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node7001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node8001.geometry}
          material={materials['#855A1DFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node9001.geometry}
          material={materials['#F2E2C5FF.003']}
        />
      </group>
      <group position={[0.461, 0.072, -1.907]} rotation={[1.561, 0.003, 0.787]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1001.geometry}
          material={materials['x1.002']}
          position={[-0.01, -0.005, 1.122]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.night_stand_2.geometry}
        material={materials['Material.005']}
        position={[0.755, 0.007, 1.814]}
        rotation={[Math.PI, -1.543, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.night_stand_1.geometry}
        material={materials['Material.006']}
        position={[0.742, 0.007, 2.217]}
        rotation={[Math.PI, -1.543, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.slap.geometry}
        material={materials['Material.007']}
        position={[1.058, 0.003, -2.503]}
        rotation={[1.571, -0.002, -1.562]}
        scale={[3, 3, 2]}
      />
      <group position={[0.79, 0.532, 2.265]} rotation={[Math.PI / 2, 0, 0.753]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato.geometry}
          material={materials['Aluminum_-_Polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato_1.geometry}
          material={materials['Fabric_(Generic)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato_2.geometry}
          material={materials['Paint_-_Enamel_Glossy_(Black)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato_3.geometry}
          material={materials['Paint_-_Metallic_(Blue)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato_4.geometry}
          material={materials['Paint_-_Enamel_Glossy_(Yellow)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato_5.geometry}
          material={materials['Paint_-_Metallic_(Dark_Grey)']}
        />
      </group>
      <group rotation={[1.571, -0.003, -1.631]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1.geometry}
          material={materials['#181818FF.002']}
          position={[-1375.709, 1021.255, -1271.302]}
          rotation={[0, 0, 0.06]}
          scale={[2.31, 0.76, 1.45]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node2.geometry}
            material={materials['#F5F5F2FF.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node3.geometry}
            material={materials['#F4F4F5FF.001']}
          />
        </mesh>
      </group>
      <group position={[-1.781, 0.951, 2.655]} rotation={[1.553, 0, 0]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1004.geometry}
          material={materials['#181818FF.003']}
          position={[0, -12.745, -0.23]}
          scale={[0.83, 1.34, 1.01]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node2003.geometry}
            material={materials['#F5F5F2FF.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node3003.geometry}
            material={materials['#F4F4F5FF.002']}
          />
        </mesh>
      </group>
      <group position={[-3.155, 1.051, 2.638]} rotation={[Math.PI / 2, 0, 3.138]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.OBJ.geometry} material={materials.Wood} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.OBJ_1.geometry}
          material={materials.Brass_A_5}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stand.geometry}
        material={materials['Material.008']}
        position={[-2.292, 0.002, 2.249]}
        scale={[0.015, 0.01, 0.015]}
      />
      <group position={[-2.283, 0.631, 2.265]} rotation={[Math.PI / 2, 0, 1.866]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001.geometry}
          material={materials['Aluminum_-_Polished.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001_1.geometry}
          material={materials['Fabric_(Generic).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001_2.geometry}
          material={materials['Paint_-_Enamel_Glossy_(Black).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001_3.geometry}
          material={materials['Paint_-_Metallic_(Blue).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001_4.geometry}
          material={materials['Paint_-_Enamel_Glossy_(Yellow).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001_5.geometry}
          material={materials['Paint_-_Metallic_(Dark_Grey).001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node1003.geometry}
        material={materials['#D7D0C0FF']}
        position={[0.726, 0.581, 1.796]}
        rotation={[1.574, -0.007, 1.926]}
        scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node10002.geometry}
          material={materials['#F7E099FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node11.geometry}
          material={materials['#E5E5E5FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node12.geometry}
          material={materials['#57D669FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node13.geometry}
          material={materials['#CAD1EEFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node14.geometry}
          material={materials['#DBDBDBFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node15.geometry}
          material={materials['#C2662EFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node16.geometry}
          material={materials['#FFFFFFFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node17.geometry}
          material={materials['#A58300FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node18.geometry}
          material={materials['#1A1A1AFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node2002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node3002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node4002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node5002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node6002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node7002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node8002.geometry}
          material={materials['#49A954FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node9002.geometry}
          material={materials['#D7D0C0FF']}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload(model)
